# SPDX-FileCopyrightText: 2026 Paul Galbraith
# SPDX-License-Identifier: BSD-3-Clause
"""OS installation scripting over agentless QEMU guest automation."""

from .blueprint import (Blueprint, BlueprintDrive, delete_blueprint,
                        load_blueprint, parse_blueprint, new_blueprint)
from .cli import main
from .home import (Context, blueprints_dir, cache_dir, documents_dir,
                   downloads_cache_dir, home, machines_cache_dir,
                   media_cache_dir, media_dir, scripts_dir, set_cache,
                   set_home)
from .interaction import GuestExec
from .interaction_agentless import AgentlessGuestExec
from .lifecycle import (Qmp, create_hdd_image, find_qemu, find_qemu_img,
                        stop)
from .machine import (Machine, cursor_menu_select, screen_text,
                      screenshot, send_keys, send_text, wait_text)
from .machines import (apply_blueprint, create, create_machine,
                       destroy_machine, eject_media, get_machine_dir,
                       insert_media, list_machines, load_machine_state,
                       machine_dir_path, machine_drive_args, mark_stopped,
                       recreate_machine, resolve_machine, set_boot_order,
                       start_machine,
                       stop_machine)
from .media import (MediaDefinition, MediaItem, ResolvedMedia,
                    fetch_media, resolve_media, clean_downloads,
                    clean_media, delete_media, list_media)
from .properties import (get_property, set_property, unset_property,
                         list_properties)
from .script_nodes import ScriptParseError
from .script_parser import (Condition, Handler, Phase, Property, Script,
                            Statement, load_script, parse_script)
from .script_runner import (ScriptCheck, ScriptRun, ScriptRuntimeError,
                            check_script, execute_script, run_script)

__all__ = [
    "Blueprint",
    "BlueprintDrive",
    "Condition",
    "Handler",
    "Machine",
    "Qmp",
    "Script",
    "ScriptCheck",
    "ScriptParseError",
    "ScriptRun",
    "ScriptRuntimeError",
    "Phase",
    "Property",
    "Statement",
    "AgentlessGuestExec",
    "Context",
    "GuestExec",
    "apply_blueprint",
    "create",
    "create_hdd_image",
    "create_machine",
    "cursor_menu_select",
    "delete_blueprint",
    "delete_media",
    "destroy_machine",
    "eject_media",
    "get_machine_dir",
    "insert_media",
    "MediaDefinition",
    "MediaItem",
    "ResolvedMedia",
    "blueprints_dir",
    "cache_dir",
    "clean_downloads",
    "clean_media",
    "documents_dir",
    "downloads_cache_dir",
    "find_qemu",
    "find_qemu_img",
    "get_property",
    "home",
    "list_machines",
    "list_media",
    "list_properties",
    "load_blueprint",
    "load_script",
    "load_machine_state",
    "machine_dir_path",
    "machine_drive_args",
    "machines_cache_dir",
    "main",
    "mark_stopped",
    "media_cache_dir",
    "media_dir",
    "new_blueprint",
    "parse_blueprint",
    "parse_script",
    "recreate_machine",
    "resolve_machine",
    "screen_text",
    "screenshot",
    "scripts_dir",
    "send_keys",
    "send_text",
    "set_boot_order",
    "set_cache",
    "set_home",
    "set_property",
    "start_machine",
    "stop",
    "stop_machine",
    "unset_property",
    "wait_text",
    "execute_script",
    "check_script",
    "run_script",
]
