# SPDX-FileCopyrightText: 2026 Paul Galbraith
# SPDX-License-Identifier: BSD-3-Clause
"""OS installation scripting over agentless QEMU guest automation."""

from .blueprint import (Blueprint, BlueprintDrive, load_blueprint,
                        parse_blueprint)
from .cli import main
from .home import (blueprints_dir, cache_dir, documents_dir,
                   downloads_cache_dir, drives_dir, home, machines_cache_dir,
                   media_cache_dir, media_dir, scripts_dir, set_home)
from .interaction import GuestExec
from .interaction_agentless import AgentlessGuestExec
from .lifecycle import (Qmp, create_hdd_image, find_qemu, find_qemu_img,
                        stop)
from .machine import (Machine, cursor_menu_select, screen_text,
                      screenshot, send_keys, send_text, wait_text)
from .machines import (create, create_from_blueprint, destroy,
                       eject_media, insert_media, list_machines,
                       load_machine_state, machine_dir_path,
                       machine_drive_args, mark_stopped, resolve_machine,
                       set_boot_order, short_id,
                       start as start_cached_machine,
                       stop as stop_cached_machine)
from .media import (MediaDefinition, MediaItem, ResolvedMedia,
                    fetch_media, resolve_media)
from .script import (Condition, EmbeddedMedia, ExpectBranch, Script,
                     ScriptParseError, State, Statement, load_script,
                     parse_script)
from .script_runner import (ScriptRun, ScriptRuntimeError,
                            execute_script, run_script)
from .workflows import (MachineConfig, Runner, run_guest_program, run_task,
                        start)

__all__ = [
    "Blueprint",
    "BlueprintDrive",
    "Condition",
    "EmbeddedMedia",
    "ExpectBranch",
    "Machine",
    "Qmp",
    "Runner",
    "Script",
    "ScriptParseError",
    "ScriptRun",
    "ScriptRuntimeError",
    "State",
    "Statement",
    "MachineConfig",
    "AgentlessGuestExec",
    "GuestExec",
    "create",
    "create_from_blueprint",
    "create_hdd_image",
    "cursor_menu_select",
    "destroy",
    "eject_media",
    "insert_media",
    "MediaDefinition",
    "MediaItem",
    "ResolvedMedia",
    "blueprints_dir",
    "cache_dir",
    "documents_dir",
    "downloads_cache_dir",
    "drives_dir",
    "find_qemu",
    "find_qemu_img",
    "home",
    "list_machines",
    "load_blueprint",
    "load_script",
    "load_machine_state",
    "machine_dir_path",
    "machine_drive_args",
    "machines_cache_dir",
    "main",
    "mark_stopped",
    "media_cache_dir",
    "media_dir",
    "parse_blueprint",
    "parse_script",
    "resolve_machine",
    "run_guest_program",
    "run_task",
    "screen_text",
    "screenshot",
    "scripts_dir",
    "send_keys",
    "send_text",
    "set_boot_order",
    "set_home",
    "short_id",
    "start",
    "start_cached_machine",
    "stop",
    "stop_cached_machine",
    "wait_text",
    "execute_script",
    "run_script",
]
